[package]
categories = ["cryptography", "development-tools"]
description = "An experimental implementation of gitoids in Rust"
edition = "2021"
homepage = "https://omnibor.io/"
keywords = ["gitbom", "omnibor", "sbom", "gitoid"]
license = "Apache-2.0"
name = "gitoid"
readme = "../README.md"
repository = "https://github.com/omnibor/omnibor-rs"
version = "0.1.5"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
hex = "0.4.3"
sha1 = "0.10.6"
sha2 = "0.10.8"
url = "2.4.1"
