[package]
categories = ["cryptography", "development-tools"]
description = "An experimental implementation of gitoids in Rust"
edition = "2021"
homepage = "https://gitbom.dev"
keywords = ["gitbom", "sbom", "gitoid"]
license = "Apache-2.0"
name = "gitoid"
readme = "../README.md"
repository = "https://github.com/git-bom/gitbom-rs"
version = "0.1.0"

[dependencies]
futures = "0.3.21"
hex = "0.4.3"
im = "15.1.0"
pin-project = "1.0.10"
sha1 = "0.10.1"
sha2 = "0.10.2"
tokio = {version = "1.17", features = ["io-util", "fs", "rt", "macros"]}

