name: Rust tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build [no_std]
      run: cargo build --verbose
    - name: Run tests [no_std]
      run: cargo test --verbose
    - name: Build [std]
      run: cargo build --verbose --features=std
    - name: Run tests [std]
      run: cargo test --verbose --features=std
    - name: Run clippy
      run: cargo clippy
